site_name: "Caudalis"
site_url: "https://neestoralvz.github.io/caudalis"

nav:
  - Inicio: index.md
  - Acerca de:
      - Misión y Visión: about/mission.md
      - Identidad: about/identity.md
      - Marca:
          - Nombre: about/branding/name.md
          - Estilo: about/branding/style.md
  - Desarrollo:
      - Navegación:
          - Plan de Navegación: development/navigation/plan_navegacion.md
          - Iteración 1: development/navigation/iteracion_1.md
          - Iteración 2: development/navigation/iteracion_2.md
      - Marca:
          - Plan Inicial: development/branding/plan_inicial.md
          - Iteración 1: development/branding/iteracion_1.md
          - Iteración 2: development/branding/iteracion_2.md
          - Iteración 3: development/branding/iteracion_3.md
          - Iteración 4: development/branding/iteracion_4.md

theme:
  name: material
  language: "es"
  palette:
    - scheme: slate
      primary: "#0D47A1"  # Azul Profundo
      accent: "#FFD600"  # Ámbar (CTA / acentos)
      toggle:
        icon: material/brightness-4
        name: "Cambiar a modo claro"

    - scheme: default
      primary: "#0D47A1"  # Azul Profundo
      accent: "#FFD600"  # Ámbar (CTA / acentos)
      toggle:
        icon: material/brightness-7
        name: "Cambiar a modo oscuro"

  features:
    - navigation.top
    - navigation.tabs

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - footnotes
  - tables
  - def_list

plugins:
  - search:
      lang: es

docs_dir: docs
# site_dir: site
