site_name: "Caudalis"
site_url: "https://neestoralvz.github.io/caudalis"  # Ajusta si cambias el nombre del repo o usas otra URL
nav:
  - Inicio: index.md
  - Misión y Visión: mision_vision.md
  - Elección de Nombre: eleccion_nombre.md
  - Plan:
      # Ajusta según los archivos que tengas en docs/plan
      # - Iteración 1: plan/iteracion_1.md
      # - Iteración 2: plan/iteracion_2.md
      # - etc.
theme:
  name: "material"
  language: "es"
  palette:
    - scheme: slate         # Modo oscuro por defecto
      primary: "indigo"
      accent: "deep purple"
      toggle:
        icon: material/brightness-4
        name: "Modo claro"
    - scheme: default       # Modo claro
      primary: "indigo"
      accent: "deep purple"
      toggle:
        icon: material/brightness-7
        name: "Modo oscuro"
  features:
    - navigation.top
    - navigation.tabs
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - footnotes
  - tables
  - def_list
plugins:
  - search:
      lang: es
docs_dir: "docs"
