site_name: "Caudalis"
site_url: "https://neestoralvz.github.io/caudalis"

nav:
  - Inicio: index.md
  - Misión y Visión: mision_vision.md
  - Elección de Nombre: eleccion_nombre.md
  - Guía de Estilo: estilo.md
  - Plan:
      - Plan Inicial: plan/plan_inicial.md
      - Iteración 1: plan/iteracion_1.md
      - Iteración 2: plan/iteracion_2.md
      - Iteración 3: plan/iteracion_3.md
      - Iteración 4: plan/iteracion_4.md

theme:
  name: material
  language: "es"
  palette:
    - scheme: slate            # Modo oscuro por defecto
      primary: "#0D47A1"       # Azul Profundo
      accent: "#FFD600"        # Ámbar (CTA / acentos)
      toggle:
        icon: material/brightness-4
        name: "Cambiar a modo claro"

    - scheme: default          # Modo claro alternativo
      primary: "#0D47A1"       # Azul Profundo
      accent: "#FFD600"        # Ámbar (CTA / acentos)
      toggle:
        icon: material/brightness-7
        name: "Cambiar a modo oscuro"

  features:
    - navigation.top
    - navigation.tabs

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - footnotes
  - tables
  - def_list

plugins:
  - search:
      lang: es

docs_dir: docs
# site_dir: site
